Task : deblur
Version : DeepSN_Net
datasets :
  train :
    path : /mnt/ssd4/zhangcx/data/Gopro/gopro/train
    patch_size : 256
    batch_size : 32
    aug_mode : True

  test :
    path_1 : /mnt/ssd4/zhangcx/data/Gopro/gopro/test
    path_2 : /mnt/hdd0/zhangcx/Dataset/BLUR_test/HIDE
    path_3 : /mnt/hdd0/zhangcx/Dataset/BLUR_test/RealBlur_J
    path_4 : /mnt/hdd0/zhangcx/Dataset/BLUR_test/RealBlur_R


train :
  epoch : 2500
  clip_grad : True
  loss_type : mix3  #mix1\mix2\mse\Charbonnier

  load :
    inherit : True
    model : model_current.pth

  optim:
    type : AdamW #AdamW
    init_lr : !!float 8e-4
    weight_decay : !!float 1e-3
    final_lr : !!float 1e-5
    betas : [0.9,0.95]
    scheduler_type : linear #cosine

save:
  freq : 5000
  auto_freq : 500

val:
  freq : 10000 #10000
  windows : 256
