Task : derain
Version : DeepSN_Net
datasets :
  train :
    path : /mnt/hdd0/zhangcx/Dataset/derain/train/Rain11200
    patch_size : 256
    batch_size : 64
    aug_mode : True

  test :
    path_1 : /mnt/hdd0/zhangcx/Dataset/derain/test/Test100
    path_2 : /mnt/hdd0/zhangcx/Dataset/derain/test/Rain100H
    path_3 : /mnt/hdd0/zhangcx/Dataset/derain/test/Rain100L
    path_4 : /mnt/hdd0/zhangcx/Dataset/derain/test/Test1200
    path_5 : /mnt/hdd0/zhangcx/Dataset/derain/test/Test2800

train :
  epoch : 2000
  clip_grad : true
  loss_type : mix3  #mix1\mix2\mse\Charbonnier

  load :
    inherit : True
    model : model_current.pth

  optim:
    type : AdamW
    init_lr : !!float 1e-3
    weight_decay : !!float 1e-4
    final_lr : !!float 1e-5
    betas : [0.9,0.95]
    scheduler_type : linear #cosine

save:
  freq : 5000
  auto_freq : 500

val:
  freq : 1000
  windows : 256
